stages:
- test
- build

test:
  stage: test
  tags:
    - shell
    - vpsfree
  script:
    - cargo test --all

build:
  stage: build
  tags:
    - shell
    - vpsfree
  script:
    - cargo build --release
