[workspace]

members = [
    "actixasync",
    "actixcomplex/backend",
    # "actixcomplex/frontend", TODO: implement front end in yaw
    "actixfileupload",
    "actixssl",
    "async-std",
    "hyper",
    "hyperssl",
    "warp",
    "warpssl",
    "parser",
    "tokio-async",
]
