name: build

on: [push]

jobs:
  build-linux: 
    runs-on: ubuntu-latest
    steps:
    - name: Install sqlite
      run: sudo apt-get install libsqlite3-dev

    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build 
    - name: Run tests
      run: cargo test
